### ISSUE TITLE
feature request - future parser compatibility

### ISSUE THREAD

**Issue by mvernimmen-CG** [GRIF-IRFU/puppet-omd#27]
Hi,

Currently the module does not seem to support the future parser. When enabling the future parser I get the following puppet output:

```
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Duplicate declaration: Omd::Check_mk::Build_exported_resources[all] is already declared; cannot redeclare at /export/data/puppet/environments/CG_20534_puppetserver/modules/omd/manifests/check_mk/build_exported_resources.pp:34:5 on node host.domain.tld
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I've had a quick look at the code but couldn't immediately spot the reason. I suspect that the 'hack'  mentioned in the top of build_exported_resources.pp no longer works when the future parser is enabled.

Is this something you would be willing to fix?

**Comment by fschaer** [comment]
Hi,

Yes, I’d be willing to fix that as I’m working on puppet4 integration for the rest of my infrastructure anyways… I’ll take a look at this ASAP.

Cheers

**Comment by mvernimmen-CG** [comment]
Tried it again with the latest commit (from oct 2016) but the error remains the same.

**Comment by fschaer** [comment]
Hi,

That's normal, I've been overloaded and unable to look at this recently :'(
I'll take a look now to see if I can spot anything obvious (if my puppet4 server vm works ;) )

**Comment by fschaer** [comment]
Hi,

I don't get that issue when enabling the future parser or using a pp4 server : are you using the build_exported_resources define directly ?

The issue you're seeing might also be caused by the comparison between the false boolean and the $allow_duplicates param on line 20 (not sure) since according to the puppet4 migration guidelines, comparing types should not be possible anymore (this comparing a string to a boolean... ?)

But then I should get an error on my side, unless my puppet4 server/puppet3 future parser are outdated compared to yours. What versions are you using ?

**Comment by mvernimmen-CG** [comment]
I'm on 3.8.7 for both master and agents. I created a separate environment for this and set 
`parser = future` on the master. The agent runs on a CentOS 7.2 machine that OMD is monitoring (it's not the OMD server that I'm doing the run on yet, first all the nodes that should get monitored).
I'm not calling build_exported_resources directly from anywhere, there are only a few entries for build_exported_resources in our entire puppet setup and they are all in the omd module:
puppet/environments/VH_5930_puppet4omd/modules/omd/manifests/check_mk/build_exported_resources.pp:define omd::check_mk::build_exported_resources(
puppet/environments/VH_5930_puppet4omd/modules/omd/manifests/check_mk/build_exported_resources.pp:    ensure_resource('omd::check_mk::build_exported_resources', "${realname}", { monitoring_network => $monitoring_network , monitoring_netmask => $monitoring_netmask })
puppet/environments/VH_5930_puppet4omd/modules/omd/manifests/check_mk/addtag.pp:  omd::check_mk::build_exported_resources {$tag_sites : allow_duplicates => '#', monitoring_network=>$monitoring_network , monitoring_netmask => $monitoring_netmask}
puppet/environments/VH_5930_puppet4omd/modules/omd/manifests/check_mk/addtag.pp:  Omd::Check_mk::Tag["$tagname"] -> Omd::Check_mk::Build_exported_resources <| |>

About line 20, I looked up how booleans are used with the future parser (https://docs.puppet.com/puppet/3.8/future_lang_data_boolean.html) and I think it looks fine. But when I use is_a to detect the type, $allow_duplicates turns out to be a string with the value '#'. Which is a bit odd for a variable that should be a boolean :)
I suspect this line is the cause:
`./addtag.pp:46:  omd::check_mk::build_exported_resources {$tag_sites : allow_duplicates => '#', monitoring_network=>$monitoring_network , monitoring_netmask => $monitoring_netmask}`

**Comment by mvernimmen-CG** [comment]
When I add some code to force the # value to be a boolean false, the reported problem goes away. I do run into a new problem:
`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid tag 'checkmk_conf_all#puppet_lastrun' at /puppet/environments/VH_5930_puppet4omd/modules/omd/manifests/check_mk/build_exported_resources.pp:107 on node xxxxx.cgnet.nl
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

This is because tags are not allowed to have #'s in them (https://docs.puppet.com/puppet/4.9/lang_reserved.html#tags).

**Comment by fschaer** [comment]
Hi,

The # char is only used to split strings on it, it should not be a tag, but anyway.
The thing is a string can be interpreted in a Boolean context, but this has changed with puppet4 a bit even if it should (?) not affect us in the present case – I’ll check if I can replace the Boolean with either undef or an empty string for the sake of code coherence anyway, sure… but I’d like to reproduce your issue first…

I’m also on 3.8.7, but I can’t change my production master – I can try to compile the catalog on it with the future parser on though, to see if this changes anything to running on the client with that option…

**Comment by mvernimmen-CG** [comment]
Running the agent with the future parser commandline option won't show you the problem, because the compiling of the catalog is done on the master, not on the agent. So the future parser must be enabled on the master.

Perhaps you could either clone your production master so you have a separate machine to play with, or you could create a separate environment (https://docs.puppet.com/puppet/3.8/environments_configuring.html) ?

Alternatively if cloning or an extra environment is not possible, perhaps you could disable puppet for a moment on all nodes (using mco or some other distributed command system), enable the future parser, restart the master process and then execute on 1 test node.
or use vagrant. Ahh... there are so many options :)

The tag is specifically set in build_exported_resources. You're using # as a string separator, and the string is added as a tag to the file being written. Puppet 4 doesn't allow the # to be contained in tag values, which breaks ithe run. Perhaps you can use a different character? Or if the tag isn't needed on the file, the line can be removed?

`     @@file { "${mk_confdir}/${mkhostname}.mk":
         content => template("omd/collection.mk.erb"),
         notify  => Exec["checkmk_inventory_${mkhostname}_${name}"],
         tag     => ["checkmk_conf_${name}",'check_mk_exported_data'],
     }`
In my case, $name == "all#puppet_lastrun", causing a problem.

**Comment by fschaer** [comment]
Hi,

I'll check how/if changing the # char to something else doesn't break anything, and if that might fix that issue - but as I said, I also retrieved the catalog from a real puppet4 (well, a VM, but not just the future parser) server and got no catalog compilation issue. 

Will report as soon as I checked that and eventually commited the changes - there would be more changes coming in proably, as I haven't synced github recently and probably fixed a few other glitches since my last sync

**Comment by mvernimmen-CG** [comment]
Please do let me know if there is anything I can assist with?

**Comment by fschaer** [comment]
Hi,

I’ll hopefully upgrade my agents and master next week to puppet4 (I got almost everything ok this week) : as I already validated the omd configs are ok when served from both a puppet server, I can see next week if there’s an incompatibility with the puppet agent 4, and I will update anyway the tags as you suggested – and push the change off course

Sorry, this takes time… :/

In the mean time, it would be great if you could confirm that’s the tags that are the issue by patching on your side… ?

Cheers

**Comment by mvernimmen-CG** [comment]
Hi,

Yes when I change the # to : (which is allowed and luckily not part of the regsubst in addtag.pp) in addtag and build_exported_resources.pp it parses properly. I have not yet fully verified that it all functions as it should, but the basics seem ok with that change.

**Comment by fschaer** [comment]
Ok thanks.

I’ll implement the changes on my side then (I’m almost finished with my puppet4 upgrade)

**Comment by fschaer** [comment]
Hi again.

So I just pushed  78cd20c  into master a fix removing the # char from the tags. This is working correctly on my puppetserver (2.7.2-1), and on the puppet agent 4.10.

Would be nice if you could confirm this commit fixes your issue which I wasn't able to reproduce even with puppet4 as a server, which is weird as the # char indeed was forbidden but still working.

I have another batch of fixes ready to push, that will allow for new cool stuff as check-mk-core or an updated agent version (which requires an update to check-mk I believe)

**Comment by mvernimmen-CG** [comment]
Hi,

Thanks, I tested it, and that part works, but the underlying issue for the duplicate declaration still exists. I can work around it using this diff to build_exported_resounces.pp:
`
22,31c20
<    if ($allow_duplicates == '_XxX_') {
<      $allow_duplicates2 = false
<    } else {
<      $allow_duplicates2 = $allow_duplicates
<    }
<
<
<   # a non empty string is true, and in puppet4, the empty string *also* is true (false in puppet3), hence base the decision on "undef or anything"
<   if $allow_duplicates2 {
---
>   if $allow_duplicates { # a non empty string is also a true
33,35c22,24
<     $c = type3x($allow_duplicates2) ? {
<           'string' => "${allow_duplicates2}",
---
>     $c = type3x($allow_duplicates) ? {
>           'string' => "${allow_duplicates}",
`
This is needed because the variable $allow_duplicates that is given to omd::check_mk::build_exported_resources is always _XxX_ (used to be #) in my case. So when multiple resources are run, that causes problems (see initial post about duplicate declaration error). My patch makes sure that _XxX_ is considered false (would be true otherwise) and says that duplicates are not allowed in the case the define is not called with an explicit true for $allow_duplicates.

I'm not sure about how that would impact the rest of the code, especially the calling code to omd::check_mk::build_exported_resources, but in my case it parses with puppet 3 with both future parser on and off and seems to work fine.

**Comment by fschaer** [comment]
OK thanks.
I'll test this on my side and see if it might break something, then push that change if it's ok.

I admit I'm quite unhappy with this part of the module, I'd like to rework it and use a more modern way of doing this, if possible... maybe with puppet4-only code... I'll see what I can do once this issue is closed. 

Let's try to fix this one...

**Comment by fschaer** [comment]
Hi again,

How are you adding tags ? Your change would break things, as the "allow_duplicates" param is used to give the string on which the exported resources are allowed to be duplicated. (this really needs to be rewritten...)

**Comment by fschaer** [comment]
auxiliary question : have you tried with a real puppetserver, not with the future parser (since puppet3 is EOL...).

The should be no such duplicate declaration as it's the whole purpose of that part of the code to avoÏd duplication, and futhermore, the "build_exported_resources" define is only called in 2 places : 
- by the "addtag" define with namevars changed into omdsite_splitchar_tag
- by the build_exported_resources itself with an "ensure_resource" on the namevar "omdsite" only, but making sure that there is then no infinite recursion

You duplicate resource happens on the 2nd call, where there is an ensure_resource: even if this part of the code was called twice, that's the purpose of the ensure_resource to not duplicate resources... hence I don't understand.

Ar you adding multiple tags using the ENC or something like that ?

**Comment by mvernimmen-CG** [comment]
Hi,

I have not tried a real puppetserver yet, because I wanted to be sure that everything works with the future parser first. Since I have a working workaround (or so it seemed ;) ) I can continue with fixing any other future parser problems I run into. Once OMD is the last thing out there blocking, I'll go and give puppetserver a try and see what it does for this specific problem.

We set tags like this:
```
  # hosts
  define addHost ($hTitle, $hName, $site, $tags){
	  omd::check_mk::addhost{
	    "${hTitle}":
	      hostname => $hName,
	      site     => $site,
	      tags     => $tags
	  }
  }
  # Get omd_host config from hiera
  $hostSettings = hiera_hash('omd::hosts', 'Could not find hiera hash. maybe you made a typo?', 'omd_hosts')    
  # create hosts with it:
  create_resources(addHost, $hostSettings)
  
	# Host Aliasses
	# based on the omd_host config in hiera
	omd::check_mk::var::set {'extra_host_conf#alias': site=>'mon', content=>'[]' }
	define addAlias ($hTitle, $hName, $site, $tags ){
        omd::check_mk::var::append {"extra_host_conf#alias|${hTitle}": site=>'mon', content=>"[('${hTitle}' , ['${hName}'])]" }
	}
  create_resources(addAlias, $hostSettings)

  $legacy_service_settings = hiera_hash('omd::legacy_service', 'Could not find hiera hash. maybe you made a typo?', 'omd_legacy_service')    
  # create legacy services with it:
  create_resources(add_legacy_service, $legacy_service_settings)
  
	define add_legacy_service ($checkname, $command, $mk_tags, $mk_hosts, $perfdata ){
    omd::check_mk::legacy::service {"${checkname}": command => "$command",site=>'mon', mk_tags=>$mk_tags, mk_hosts=>$mk_hosts, perfdata=>$perfdata }
	}
```

And in hiera there is a list like this for hosts
```
  td006:
    hTitle: 'host006'
    hName: 'app06.t'
    site: 'mon'
    tags: 'lan|cmk-agent|tcp|TEST_BE|prod|app1|unix'
  td007:
    hTitle: 'host007'
    hName: 'app07.t'
    site: 'mon'
    tags: 'lan|cmk-agent|tcp|TEST_FE|prod|app2|unix'
```

or like this for the legacy services
```
  emc_disk:
    checkname: emc_disk
    command: check_emc!-t disk
    mk_tags:
    mk_hosts: ['host20-a','host020-b']
    perfdata: true
  emc_energy:
    checkname: emc_energy
    command: check_emc!-t power
    mk_tags:
    mk_hosts: ['host020-a','host020-b']
    perfdata: true
```

Perhaps our usage of the omd module violates some implicit assumptions done?

**Comment by fschaer** [comment]
I'm not using the module this way, I'll test if the create_resources clashes with the module's "ensure_resource" calls... maybe we hit some kind of bug ...

**Comment by mvernimmen-CG** [comment]
I've made a lot of progress in getting my puppet setup ready for puppet 4 so now I was able to test against puppeserver instead of 'puppet server'. When running the host against puppetserver 1.2.0 with futureparser=true, I unfortunately get the same duplicate resource error as I did with 'puppet server' 3.7.8
I know 1.2.0 is old, but it's a step towards the long walk to v4.

**Comment by fschaer** [comment]
closing as puppet4 id gone, and things are working ok with puppet5. Please reopen if you still face that kind of thing.

Thanks
